#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=1 python main.py \
    --seed 0 \
    --alpha_edl 1.2 \
    --alpha_uct_guide 0.2 \
    --amplitude 0.2 \
    --alpha2 0.8 \
    --rat_atn 5 \
    --k 5 \
    --interval 200 \
    --max_seqlen 60 \
    --lr 3e-5 \
    --dataset_name ActivityNet1.2 \
    --path_dataset Here is your local dataset path \
    --num_class 100 \
    --use_model DELU_ACT \
    --max_iter 22000 \
    --dataset AntSampleDataset \
    --project DDG_ACT \
    --action_threshold 0.5 \
    --background_threshold 0.5 \
    --top_k_rat 10 \
    --similarity_threshold 0.8 \
    --AWM DDG_Net \
    --model_name ActivityNet-DDG_Net \
    --alpha6 0.5 \
    --temperature 0.5 \
    --weight 2 \
    --alpha5 1.7 \
    --use_causal_intervention 1 \
    --abs_atn_threshold 0.9 \
    --use_consistence_loss 1 \
    --consistence_threshold 0.7 \
    --consistence_proposal_threshold 0.5 \
    --feat_level_loss_weight 1.5 \
    --attn_level_loss_weight 1.5
